# -*- coding: utf-8 -*-
"""basic.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1xO-J1aRysaADEuDTARAIC3o30Oz1kA45
"""

#switching with temp
a=4
b=5
temp=a
a=b
b=temp
print(a)
print(b)

#switching without temp
a=5
b=4
a+=b
a-=b

print(a)
print(b)

#find min among n variable

l=[9,7,2,12,45,78,-20]
def minimum(l):
  temp=l[0]
  for i in l:
    if temp>i:
      temp=i
  return temp

print(minimum(l))

#find max among n variable

l=[9,7,2,12,45,78,-20]
def maximum (l):
  temp=l[0]
  for i in l:
    if temp<i:
      temp=i
  return temp

print(maximum(l))

#find sum among n variable

l=[9,7,2,12,45,78,-20]
def sum(l):
  temp=0
  for i in l:
    temp+=i
  return temp

print(sum(l))

#generate student mark

mark=int(input("mark:"))

if(mark>=90)and(mark<=100):
    print("s")

elif(mark>=80)and(mark<90):
    print("a")

elif(mark>=70)and(mark<80):
    print("b")

elif(mark>=60)and(mark<70):
    print("c")

elif(mark>=50)and(mark<60):
    print("d")

elif(mark>=0)and(mark<50):
    print("fail")

else:
    print("invalid")

#word count

def user_name(sentence):
    d={}
    counter=1
    for word in sentence:
        if word not in d:
            d[word]=1
        else:
            d[word]=counter
    return d
print(user_name("how r u"))